import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region Clarity
	{
		name: '清晰体验',
		desc: '纸鹿学长太强了orz。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
			{
				author: '纸鹿摸鱼处',
				sitenick: '杂记本',
				title: '古怪杂记本',
				desc: '一个什么都可能会写的博客',
				link: 'https://blog.guuguai.site/',
				feed: 'https://blog.guuguai.site/atom.xml',
				icon: 'https://cravatar.cn/avatar/646331BFF8F19A0E05679C3CC0FC54D6',
				avatar: 'https://cdn.libravatar.org/avatar/646331bff8f19a0e05679c3cc0fc54d6?s=160',
				archs: ['Nuxt', 'Netlify'],
				date: '2023-12-23',
				comment: '高中同学，技术好友，爱好番剧/折腾。',
			},
		],
	},
	// #endregion
	// #region 网上邻居 since 2024
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'isYangs',
				desc: '一个前端Bug构造师的博客',
				link: 'https://www.isyangs.cn/',
				feed: 'https://www.isyangs.cn/feed.xml',
				icon: 'https://www.isyangs.cn/favicon.svg',
				avatar: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg',
				archs: ['Vue', '国内 CDN'],
				date: '2024-01-29',
				comment: '高中时认识的小学校友，目前从事前端开发。',
			},
			{
				author: 'KazariEX',
				sitenick: '微光档案',
				desc: '故事就是只为你一个人而存在的世界',
				link: 'https://archive.bikari.top/',
				feed: 'https://archive.bikari.top/feed',
				icon: 'https://archive.bikari.top/image/favicon.svg',
				avatar: getGithubAvatar('KazariEX'),
				archs: ['Nuxt', 'Netlify'],
				date: '2024-01-30',
				comment: 'Vue.js Member，前端大手子。',
			},
			{
				author: '恩泽',
				sitenick: 'Colsrch',
				title: 'Colsrch的小破站',
				desc: '愿多年以后，我可以酌一杯清酒，烂醉如泥，梦中回到我们的曾经。',
				link: 'https://colsrch.cn/',
				feed: 'https://colsrch.cn/atom.xml',
				icon: getFavicon('colsrch.cn'),
				avatar: 'https://bu.dusays.com/2022/02/23/cb173cbdcc7c6.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-01',
				comment: '鸽王，去哪里发展了？',
			},
			{
				author: '桜紺狸',
				sitenick: '部落阁',
				title: '桜紺狸の部落阁',
				desc: '一个闲聊萌新动漫技术交流站',
				link: 'https://www.skira.top/',
				feed: 'https://www.skira.top/feed.xml',
				icon: 'https://www.skira.top/img/skira.ico',
				avatar: 'https://www.skira.top/img/lemonsuka.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-02-01',
				comment: '搞机发烧友，小众系统爱好者，前端研究员。',
			},
			// {
			// 	author: '小李同学',
			// 	sitenick: 'Coding',
			// 	title: '小李同学 Coding',
			// 	desc: '一支努力变强的小彩笔',
			// 	link: 'https://blog.xxfer.cn/',
			// 	feed: 'https://blog.xxfer.cn/rss.xml',
			// 	icon: getFavicon('blog.xxfer.cn'),
			// 	avatar: getGithubAvatar('JJLibra'),
			// 	archs: ['Hexo', '国内 CDN'],
			// 	date: '2024-02-01',
			// 	comment: '瓜大网安学长。',
			// 	error: '域名2025-10-28过期',
			// },
			{
				author: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://blog.zhheo.com/img/favicon4.0.webp',
				avatar: 'https://bu.dusays.com/2022/12/28/63ac2812183aa.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-02',
				comment: '知名博主，其博客设计风格被众多人借鉴。',
			},
			{
				author: 'Revincx',
				sitenick: '小破站',
				title: 'Revincx的小破站',
				link: 'https://blog.revincx.icu/',
				feed: 'https://blog.revincx.icu/atom.xml',
				icon: 'https://blog.revincx.icu/images/favico.png',
				avatar: 'https://weavatar.com/avatar/20eed6a268787c9a751165bc1ec56e90',
				archs: ['Hexo', 'Vercel'],
				date: '2024-02-05',
				comment: '折腾。',
			},
			{
				author: 'L1nSn0w',
				title: 'L1nSn0w\'s Site',
				desc: '无限进步.🎈',
				link: 'https://blog.vaaat.com/',
				feed: 'https://blog.vaaat.com/index.xml',
				icon: 'https://blog.vaaat.com/favicon.ico',
				avatar: getGithubAvatar('lin-snow'),
				archs: ['Astro', '国内 CDN'],
				date: '2024-02-14',
				comment: '广工学弟。',
			},
			{
				author: 'Yunyi',
				title: 'YUNYI BLOG',
				desc: '得闲饮茶~~~',
				link: 'https://www.yunyitang.me/',
				feed: 'https://www.yunyitang.me/atom.xml',
				icon: 'https://www.yunyitang.me/favicon/favicon.ico',
				avatar: 'https://www.yunyitang.me/img/Avatar.png',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2024-02-18',
				comment: '很有博客的味道。',
			},
			{
				author: 'Naokuo',
				desc: '请给我来亿碗三鲜面',
				link: 'https://index.naokuo.top/',
				feed: 'https://index.naokuo.top/rss2.xml',
				icon: getFavicon('index.naokuo.top'),
				avatar: 'https://yl2209.github.io/img/favicon.ico',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-02-18',
				comment: '折腾博客。',
				error: '2026-02-23 CDN配置错误',
			},
			{
				author: '晓空',
				sitenick: '空域',
				title: '晓空blog',
				desc: '探索更大的世界',
				link: 'https://blog.moeworld.tech/',
				feed: 'https://blog.moeworld.tech/feed/',
				icon: 'https://blog.moeworld.tech/wp-content/uploads/2024/08/cropped-favicon-32x32.png',
				avatar: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg',
				archs: ['WordPress', 'Cloudflare'],
				date: '2024-02-25',
				comment: '技术折腾笔记。',
			},
			{
				author: 'Kegongteng',
				desc: 'Blogger / Technophile / Student',
				link: 'https://kegongteng.cn/',
				feed: 'https://kegongteng.cn/atom',
				icon: 'https://kegongteng.cn/favicon.ico',
				avatar: 'https://weavatar.com/avatar/0b01396273cca253aa6876c020449b655a9cc12e75f921b38ac088569e814b5e',
				archs: ['Next.js', 'Netlify'],
				date: '2024-02-25',
				comment: '有不错想法的中学生。',
			},
			{
				author: '洛寒兮',
				title: 'I\'m Luochancy',
				desc: '这是个猫猫的博客喵～',
				link: 'https://www.luochancy.com/',
				feed: 'https://www.luochancy.com/feed',
				icon: 'https://www.luochancy.com/wp-content/uploads/2023/10/cropped-231026_head_image-32x32.png',
				avatar: 'https://www.luochancy.com/wp-content/uploads/2023/12/1904634_Ehaif6np.png',
				archs: ['WordPress', '国内 CDN'],
				date: '2024-03-01',
				comment: '高中生。',
			},
			{
				author: '斬風·千雪',
				sitenick: '風雪城',
				desc: '浩繁星空下的一场稚嫩的梦',
				link: 'https://blog.chyk.ink/',
				feed: 'https://blog.chyk.ink/atom.xml',
				icon: getGithubIcon('chiyuki0325'),
				avatar: getOicqAvatar('3526514925'),
				archs: ['Hexo', 'Vercel'],
				date: '2024-03-03',
				comment: 'Archlinux，折腾，大学生。',
			},
			{
				author: '清羽飞扬',
				title: 'LiuShen\'s Blog',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://blog.liushen.fun/info/avatar.ico',
				avatar: 'https://weavatar.com/avatar/92c15d4a1d99a8ee04b986a14a5f7e009e574b3383fc575005947988ccf205e2',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-06-02',
				comment: '武理工学长，西安老乡。',
			},
			{
				author: 'awaae',
				sitenick: '呓语梦轩',
				desc: '用心享受生活',
				link: 'https://blog.awaae001.top/',
				feed: 'https://blog.awaae001.top/atom.xml',
				icon: getFavicon('blog.awaae001.top'),
				avatar: getGithubAvatar('awaae001'),
				archs: ['Next.js', 'Vercel'],
				date: '2024-06-05',
				comment: '有思考的高中生。',
			},
			{
				author: '氿月',
				sitenick: '寂白沙洲冷',
				desc: 'Et in Arcadia, ego.',
				link: 'https://chuishen.xyz/',
				feed: 'https://chuishen.xyz/atom.xml',
				icon: 'https://chuishen.xyz/img/logo.png',
				avatar: 'https://cravatar.cn/avatar/57ff1222a81493a0e72782530e77b269?s=160',
				archs: ['Hexo', 'Vercel'],
				date: '2024-06-16',
				comment: '虚构文学。',
			},
			{
				author: '晚夜',
				desc: '做好量变的准备，促进事物的质变。',
				link: 'https://www.iczrx.cn/',
				feed: 'https://www.iczrx.cn/feed/',
				icon: 'https://www.iczrx.cn/favicon.ico',
				avatar: getOicqAvatar('1463656527'),
				archs: ['Typecho', '国内 CDN'],
				date: '2024-07-11',
				comment: '分享折腾与生活的高中生。',
			},
			{
				author: '太阳可以是蓝色',
				title: 'Moment Collector',
				desc: 'Live and learn. 🌱',
				link: 'https://blog.mletter.cn/',
				feed: 'https://blog.mletter.cn/rss.xml',
				icon: 'https://blog.mletter.cn/icon.svg',
				avatar: 'https://img13.360buyimg.com/ddimg/jfs/t1/239095/17/9691/19853/664d82dfF34a0990c/c4198876146be2d4.jpg',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-07-11',
				comment: '(aka 春日心动日记) 经常改博客名字，在读运维开发工程师，记录技术和生活日常。',
			},
			{
				author: '天翔TNXG',
				sitenick: '空间站',
				title: '天翔TNXGの空间站',
				desc: '明日尚未到来，希望凝于心上',
				link: 'https://www.tnxg.moe/',
				feed: 'https://www.tnxg.moe/feed',
				icon: 'https://www.tnxg.moe/favicon.ico',
				avatar: 'https://api-space.tnxg.top/avatar?s=qq',
				archs: ['Next.js', 'Cloudflare'],
				date: '2024-07-11',
				comment: '西北地区高中生，开源爱好者。',
			},
			{
				author: 'Ariasaka',
				sitenick: '小窝',
				title: 'Ariasakaの小窝',
				desc: '人有悲欢离合 月有阴晴圆缺',
				link: 'https://blog.yaria.top/',
				feed: 'https://blog.yaria.top/feed',
				icon: 'https://blog.yaria.top/favicon.ico',
				avatar: getGithubAvatar('LYXOfficial'),
				archs: ['Next.js', 'Vercel'],
				date: '2024-07-12',
				comment: '初中生，OIer，折腾博客。',
			},
			{
				author: 'Winner365',
				sitenick: '云栈',
				title: '365云栈',
				desc: '初阅不明言外意，重温方觉字中情',
				link: 'https://blog.365sites.top/',
				feed: 'https://blog.365sites.top/rss.xml',
				icon: getGithubIcon('Winner365-China'),
				avatar: 'https://blog.365sites.top/upload/avatar.png',
				archs: ['Halo', 'Cloudflare'],
				date: '2024-07-14',
				comment: '学生，折腾博客。',
				error: '文章数据库丢失，暂时关站',
			},
			{
				author: 'FloatSheep',
				title: 'FloatSheep\'s Blog',
				desc: 'On the other side of obstacles',
				link: 'https://blog.hesiy.cn/',
				feed: 'https://blog.hesiy.cn/posts/index.xml',
				icon: 'https://blog.hesiy.cn/favicon-32x32.png',
				avatar: getGithubAvatar('FloatSheep'),
				archs: ['Hugo', 'Cloudflare'],
				date: '2024-07-24',
				comment: '喜欢折腾。',
			},
			{
				author: 'Henry',
				sitenick: '一站',
				title: '一站 - Henry的博客',
				desc: 'Student / Designer / Dreamchaser',
				link: 'https://henry.city/blog/',
				feed: 'https://henry.city/blog/atom.xml',
				icon: 'https://henry.city/blog/favicon.ico',
				avatar: 'https://henry.city/blog/images/avatar.png',
				archs: ['Gridea', '服务器'],
				date: '2024-07-24',
				comment: '高中生，很有博客的味道。',
			},
			{
				author: 'iMaeGoo',
				sitenick: '空间站',
				title: '虹墨空间站',
				desc: '虹墨空间站',
				link: 'https://www.imaegoo.com/',
				feed: 'https://www.imaegoo.com/atom.xml',
				icon: 'https://www.imaegoo.com/favicon.ico',
				avatar: 'https://www.imaegoo.com/images/avatar.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-08-19',
				comment: '前端折腾。',
			},
			{
				author: 'DuckXu',
				sitenick: 'Notebook',
				title: 'DuckXu\'s Notebook',
				desc: 'DuckXu\'s Internet home',
				link: 'https://i.duckxu.com/',
				feed: 'https://i.duckxu.com/rss.xml',
				icon: 'https://kycloud3.koyoo.cn/2024080228778202408022342057562.png',
				avatar: 'https://media.duckxu.com/blogfiles/public/iduckxucom.jpg',
				archs: ['Typecho', '服务器'],
				date: '2024-08-20',
				comment: '学生，记录生活思考。',
			},
			{
				author: 'DengQN',
				title: 'DengQN\'s Blog',
				desc: '普通程序员',
				link: 'https://dengqn.com/',
				feed: 'https://dengqn.com/feed',
				icon: 'https://dengqn.com/favicon.ico',
				avatar: 'https://dengqn.com/image/headimg.png',
				archs: ['Vue', 'Cloudflare'],
				date: '2024-09-18',
				comment: '技术吐槽和运维记录。',
			},
			{
				author: 'LineXic',
				desc: '念念不忘，必有回响',
				link: 'https://www.linexic.top/',
				feed: 'https://www.linexic.top/rss.xml',
				icon: 'https://www.linexic.top/logo.png',
				avatar: 'https://www.linexic.top/avatar.webp',
				archs: ['Astro', 'Netlify'],
				date: '2024-10-02',
				comment: '前端学习，高中生活。',
			},
			{
				author: 'tinsir888',
				desc: 'Ηλύσια Πεδία',
				title: 'min hjemmeside',
				link: 'https://tinsir888.github.io/',
				feed: 'https://tinsir888.github.io/atom.xml',
				icon: getGithubIcon('tinsir888'),
				avatar: getGithubAvatar('tinsir888'),
				archs: ['Hexo', 'GitHub Pages'],
				date: '2024-10-18',
				comment: '计算机科学，留学生活。',
			},
			{
				author: 'XAOXUU',
				desc: '风暴前夕',
				link: 'https://xaoxuu.com/',
				feed: 'https://xaoxuu.com/atom.xml',
				icon: getGithubIcon('xaoxuu'),
				avatar: getGithubAvatar('xaoxuu'),
				archs: ['Hexo', '服务器'],
				date: '2024-10-26',
				comment: '产品与博客思考，本博客网站设计的重要参考。',
			},
			{
				author: 'Redish101',
				title: 'Redish101 Blog',
				desc: '学生，人，活的',
				link: 'https://blog.redish101.top/',
				feed: 'https://blog.redish101.top/feed',
				icon: getGithubIcon('Redish101'),
				avatar: getGithubAvatar('Redish101'),
				archs: ['Next.js', 'Vercel'],
				date: '2024-10-27',
				comment: '江湖人称数据库，初中生，博客开发中。',
			},
			{
				author: 'Pinpe',
				sitenick: '云端',
				title: 'Pinpe的云端',
				desc: '一个属于自己的云朵。',
				link: 'https://pinpe.top/',
				feed: 'https://pinpe.top/rss.xml',
				icon: 'https://pinpe.top/favicon/logo.png', // expected
				avatar: 'https://pinpe.top/head.jpg',
				archs: ['Astro', 'Vercel'],
				date: '2024-10-31',
				comment: '学生，奇妙幻想和思考。',
			},
			{
				author: '水氵冫',
				sitenick: '微霞',
				desc: '水风清，晚霞明',
				link: 'https://yuuu.org/',
				feed: 'https://yuuu.org/atom.xml',
				icon: 'https://cdn.yuuu.org/img/favicon-32x32.png',
				avatar: 'https://cdn.yuuu.org/img/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-11-03',
				comment: '学生，技术分享，生活。',
			},
			// {
			// 	author: '一粒微尘',
			// 	desc: '撷光以望，纳星于瞳',
			// 	link: 'https://blog.667408.xyz/',
			// 	feed: 'https://blog.667408.xyz/atom.xml',
			// 	icon: getGithubIcon('catxian'),
			// 	avatar: getGithubAvatar('catxian'),
			// 	archs: ['Hexo', 'Cloudflare'],
			// 	date: '2024-11-07',
			// 	comment: 'Hexo博客折腾，技术分享。',
			// 	error: '域名2025-09-24过期',
			// },
			{
				author: 'Tianli',
				desc: '自知之明是最可贵的知识！',
				link: 'https://blog.tianli0.top/',
				feed: 'https://blog.tianli0.top/rss.xml',
				icon: getGithubIcon('tianli0'),
				avatar: getGithubAvatar('tianli0'),
				archs: ['VitePress', '国内 CDN'],
				date: '2024-12-04',
				comment: '技术学习笔记，TianliGPT开发者。',
			},
			// #region 2025
			{
				author: '花生莲子粥',
				desc: '与世无争，不染于泥',
				link: 'https://blog.hslzz.cn/',
				icon: 'https://blog.hslzz.cn/favicon.ico',
				avatar: 'https://blog.hslzz.cn/img/avatar.png',
				archs: ['Hexo', '服务器'],
				date: '2025-01-03',
				comment: 'Linux系统配置、服务部署、Hexo优化等技术教程，',
			},
			{
				author: '伍十七',
				sitenick: 'everfu',
				title: 'Fuever\'s Blog',
				desc: '你好👋，我是伍十七，一个三流编程狮。',
				link: 'https://blog.efu.me/',
				feed: 'https://blog.efu.me/atom.xml',
				icon: 'https://blog.efu.me/favicon-32x32.ico',
				avatar: getGithubAvatar('everfu'),
				archs: ['Next.js', 'Netlify'],
				date: '2025-01-12',
				comment: 'Hexo Solitude 主题作者，经常换自己网站。',
			},
			{
				author: '鸢栀',
				sitenick: '仓库',
				title: '鸢栀的仓库',
				desc: '每天写下自己的喜欢',
				link: 'https://yuazhi.cn/',
				icon: 'https://yuazhi.cn/yuazhi.ico',
				avatar: 'https://weavatar.com/avatar/1dc444f85a6673099a47170588bbc6d7?s=96',
				archs: ['HTML', '服务器'],
				date: '2025-02-12',
				comment: '日常、前端、福瑞。',
			},
			{
				author: '葱苓',
				sitenick: '语畔',
				title: '葱苓语畔',
				desc: 'Don\'t worry, be happy.',
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/feed.xml',
				icon: 'https://blog.ciraos.top/favicon.ico',
				avatar: getGithubAvatar('ciraos'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-03-28',
				comment: '前端学习。',
			},
			{
				author: '懋和道人',
				desc: '李懋和，俗名李栋梁。书法、国画爱好者，互联网安全与前端建设者。',
				link: 'https://www.dao.js.cn/',
				feed: 'https://www.dao.js.cn/feed.php',
				icon: 'https://www.dao.js.cn/zb_users/upload/2024/09/202409191726720024363275.png',
				avatar: getOicqAvatar('466660026'),
				archs: ['PHP', '国内 CDN'],
				date: '2025-04-14',
				comment: '懋和道人，聚焦网站建设与技术，弘扬传统文化。',
			},
			{
				author: 'ZL Asica',
				title: 'ZLA 小站',
				desc: '月亮不抱你，星星会落在你怀里✨🌙',
				link: 'https://zla.pub/',
				feed: 'https://zla.pub/feed.xml',
				icon: getGithubIcon('ZL-Asica'),
				avatar: getGithubAvatar('ZL-Asica'),
				archs: ['Next.js', 'Vercel'],
				date: '2025-04-29',
				comment: '机器学习、前端开发、旅游经历。',
			},
			{
				author: '竹林里有冰',
				title: '竹林里有冰的博客',
				desc: '仍然在划水的菜鸡',
				link: 'https://zhul.in/',
				feed: 'https://zhul.in/rss.xml',
				icon: 'https://zhul.in/favicon.ico',
				avatar: 'https://static.031130.xyz/avatar.webp',
				archs: ['Nuxt', '服务器'],
				date: '2025-05-03',
				comment: '前端开发、网络配置、服务器运维及开源工具实战经验。',
			},
			{
				author: '路狐羽',
				sitenick: '羽音',
				title: '羽音 × Seraphonogram',
				desc: '一只毛茸茸的博客',
				link: 'https://blog.navifox.net/',
				icon: 'https://blog.navifox.net/favicon.ico',
				avatar: 'https://blog.navifox.net/favicon.ico',
				archs: ['VitePress', '服务器'],
				date: '2025-07-14',
				comment: 'Python、Django 等编程知识、开发工具使用及算法题解等内容。',
			},
			{
				author: 'Teror Fox',
				sitenick: '客栈',
				title: 'Teror的客栈',
				desc: '欢迎光临～',
				link: 'https://blog.trfox.top/',
				feed: 'https://blog.trfox.top/atom.xml',
				icon: 'https://blog.trfox.top/favicon.ico',
				avatar: 'https://img.trfox.top/assets/avatar.jpg',
				archs: ['Next.js', 'Vercel'],
				date: '2025-08-03',
				comment: '技术相关的木马免杀测试、服务器处理与迁移、工具美化，以及个人博客系统更新、回归记录等。',
			},
			{
				author: 'Snowykami',
				sitenick: '空间站',
				title: '粒子空间站',
				desc: '轻思若水，雪化生香',
				link: 'https://blog.sfkm.me/',
				feed: 'https://blog.sfkm.me/feed.xml',
				icon: getOicqAvatar('2751454815', OicqAvatarSize.Size100),
				avatar: getOicqAvatar('2751454815'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-08-25',
				comment: '云原生、HomeLab 搭建、网络安全、容器化、静态网站托管等领域的技术实践。',
			},
			{
				author: 'Restent Ou',
				title: 'Restent\'s Notebook',
				desc: 'Secret with Silent.',
				link: 'https://blog.gxres.net/',
				feed: 'https://blog.gxres.net/atom.xml',
				icon: 'https://library.gxres.net/images/icons/favicon.webp',
				avatar: 'https://library.gxres.net/images/avatars/gxres042.webp',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-08-28',
				comment: '前端/网络技术实践与个人记录',
			},
			{
				author: '酥米',
				title: '酥米的小站',
				desc: '终有一日，寻梦中人',
				link: 'https://www.sumi233.top/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://www.sumi233.top/favicon.ico',
				avatar: 'https://cdn.sumi233.top/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/userfb6a1018b84ce485.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2025-08-29',
				comment: '计算机网络知识，设备折腾。',
			},
			{
				author: 'kzhik',
				title: 'kzhik\'s website',
				desc: '前端/网络技术实践与个人记录',
				link: 'https://www.kzhik.cn/',
				feed: 'https://www.kzhik.cn/resources/rss.xml',
				icon: 'https://www.kzhik.cn/favicon.ico',
				avatar: 'https://www.kzhik.cn/avatar.webp',
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-08-31',
				comment: '前端/网络技术实践与个人记录',
			},
			{
				author: 'Saneko',
				sitenick: '星屿浅奈',
				title: '星屿浅奈 ✧ Saneko',
				desc: 'Do the things that I like.',
				link: 'https://saneko.me/',
				feed: 'https://saneko.me/atom.xml',
				icon: 'https://cdn.blog.saneko.me/Web/Avatar.png',
				avatar: 'https://cdn.blog.saneko.me/Web/Avatar.png',
				archs: ['Astro', '服务器'],
				date: '2025-09-09',
				comment: '曾叫ATao，技术实践与问题解决方案',
			},
			{
				author: '鲲',
				title: 'KUN\'s Blog',
				desc: 'KUN\'s moe blog, KUN IS THE CUTEST!',
				link: 'https://www.soft.moe/',
				feed: 'https://www.soft.moe/atom.xml',
				icon: 'https://www.soft.moe/favicon.ico',
				avatar: 'https://www.soft.moe/avatar.webp',
				archs: ['VitePress', 'Cloudflare'],
				date: '2025-09-13',
				comment: '鲲Gal站长，Nuxt高手，重构博客计划已搁置两年有余。',
			},
			{
				author: 'Refac7',
				title: 'RefactX Project',
				desc: '形体是简单而纯粹的，它不是完整的群体，每个形体都指向其复杂性，并最终被复杂性联系在一起。',
				link: 'https://www.refact.cc/',
				feed: 'https://www.refact.cc/rss.xml',
				icon: 'https://www.refact.cc/favicon.ico',
				avatar: 'https://www.refact.cc/avatar.png',
				archs: ['Astro', 'Vercel'],
				date: '2025-09-22',
				comment: 'RefactX 主题相关介绍、个人思考。',
				// TODO 2026-03-18 起无法访问
			},
			{
				author: 'Elykia',
				title: '致以无暇之人',
				desc: '爱莉希雅永远爱你～',
				link: 'https://blog.elykia.cn/',
				feed: 'https://blog.elykia.cn/atom.xml',
				icon: 'https://blog.elykia.cn/favicon.ico',
				avatar: getGithubAvatar('Elykia093'),
				archs: ['Hexo', '国内 CDN'],
				date: '2025-09-26',
				comment: 'Hexo 安知鱼主题美化。',
			},
			{
				author: 'VnYzm',
				title: 'VnYzm的博客',
				desc: '分享技术心得和摸鱼感想',
				link: 'https://vnyzm.top/',
				feed: 'https://vnyzm.top/extra/atom.xml',
				icon: 'https://vnyzm.top/img/favicon.ico',
				avatar: 'https://vnyzm.top/img/profile.jpg',
				archs: ['Python', 'GitHub Pages'],
				date: '2025-10-01',
				comment: '动漫观后感、游戏玩后感、技术笔记。',
			},
			{
				author: '七十二时.',
				desc: '咸鱼发呆时刻。一条咸鱼的发呆据点，也是我的实验日志。',
				link: 'https://www.qsesvick.top/',
				feed: 'https://www.qsesvick.top/feed/',
				icon: getFavicon('qsesvick.top'),
				avatar: 'https://files3.qsesvick.top/JCZY/LOGO/YJQSES.png',
				archs: ['WordPress', 'Cloudflare'],
				date: '2025-10-05',
				comment: '工具分享，博客折腾。',
			},
			{
				author: 'Sakun',
				sitenick: 'Notebook',
				title: 'Sakun Notebook',
				desc: 'Sakun Notebook',
				link: 'https://www.sakun.space/',
				feed: 'https://www.sakun.space/atom.xml',
				icon: 'https://www.sakun.space/images/favicon-32x32-next.png',
				avatar: 'https://www.sakun.space/images/avatar.png',
				archs: ['Hexo', '服务器'],
				date: '2025-10-07',
				comment: '动漫评论。',
			},
			{
				author: 'XUIOO',
				desc: '一叶障目，不见泰山；两耳塞豆，不闻雷霆。',
				link: 'https://blog.xuioo.com/',
				feed: 'https://blog.xuioo.com/rss.xml',
				icon: 'https://r2.blog.xuioo.com/GED15E4G5A1F52A1F51A.png',
				avatar: 'https://blog.xuioo.com/27c69590279fdc3be2cd7c901e3d07ad.jpg',
				archs: ['Astro', 'Cloudflare'],
				date: '2025-10-08',
				comment: '博客折腾。',
				error: '没有找到站点',
			},
			{
				author: '伏枥',
				sitenick: '伏枥之间',
				desc: '莫听穿林打叶声，何妨吟啸且徐行。',
				link: 'https://www.leehenry.top/',
				feed: 'https://www.leehenry.top/rss.xml',
				icon: 'https://www.leehenry.top/favicon/leaf-solid.svg',
				avatar: 'https://leehenry.top/friends/my-avatar-portrait.jpg',
				archs: ['Astro', '服务器'],
				date: '2025-10-15',
				comment: '生活分享、社会思考与技术探索。',
			},
			{
				author: 'Dejavu',
				title: 'Dejavu\'s Blog',
				link: 'https://blog.dejavu.moe/',
				feed: 'https://blog.dejavu.moe/index.xml',
				icon: 'https://blog.dejavu.moe/favicon.ico',
				avatar: 'https://blog.dejavu.moe/avatar.webp',
				archs: ['Hugo', 'Cloudflare'],
				date: '2025-10-23',
				comment: '记录技术、生活、思考。',
			},
			{
				author: '广树',
				sitenick: '维基萌',
				desc: '萌即是正义！时不时分享一些ACG活动记录与有趣代码的小站！',
				link: 'https://panda.wikimoe.com/',
				feed: 'https://panda.wikimoe.com/rss/blog',
				icon: 'https://panda.wikimoe.com/upload/siteImg/siteFavicon.png',
				avatar: 'https://panda.wikimoe.com/upload/avatar/65994c0f3af05a21862459e9.webp',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-10-30',
				comment: '游戏数据/圣地巡礼/代码笔记。',
			},
			{
				author: 'imlonghao',
				desc: '非专业人士的非专业博客',
				link: 'https://imlonghao.com/',
				feed: 'https://imlonghao.com/feed.xml',
				icon: 'https://imlonghao.com/favicon.ico',
				avatar: 'https://imlonghao.com/favicon.ico',
				archs: ['Golang', '服务器'],
				date: '2025-10-31',
				comment: '网络安全与实践。',
			},
			{
				author: '灯火不休时',
				desc: '所爱隔山海，山海不可平；所念皆星河，星河不可及',
				link: 'https://blog.dhbxs.top/',
				feed: 'https://blog.dhbxs.top/feed.xml',
				icon: 'https://file.dhbxs.top/2026/01/nllahmfi.png',
				avatar: 'https://file.dhbxs.top/2026/01/nllahmfi.png',
				archs: ['Halo', '国内 CDN'],
				date: '2025-11-01',
				comment: '深度学习、大数据与软件工程学习笔记。',
			},
			{
				author: '千緒',
				sitenick: '記緒漂流',
				desc: '于记忆之川，泛思绪之舟。',
				link: 'https://ttio.cc/',
				feed: 'https://ttio.cc/feed.xml',
				icon: 'https://ttio.cc/favicon.ico',
				avatar: getGithubAvatar('tuyuritio'),
				archs: ['Astro', 'Cloudflare'],
				date: '2025-11-12',
				comment: 'ThoughtLight 博客主题作者，记录开发体验与日留生活。',
			},
			{
				author: '异想之旅',
				desc: '异想之旅のBlog',
				link: 'https://yxzl.dev/',
				icon: 'https://yxzl.dev/favicon.ico',
				avatar: 'https://yxzl.dev/favicon.ico',
				archs: ['VuePress', 'Cloudflare'],
				date: '2025-11-13',
				comment: 'Python、Vue与算法。',
			},
			{
				author: 'iamyukino',
				sitenick: '雨雪冰屋',
				desc: '一隅雨雪一炉窝，可能会融化持久堆？',
				link: 'https://iamyukino.cn/blog/',
				feed: 'https://iamyukino.cn/atom.xml',
				icon: 'https://iamyukino.cn/favicon.ico',
				avatar: 'https://iamyukino.cn/blog/assets/home/home.jpg',
				archs: ['Astro', '服务器'],
				date: '2025-11-25',
				comment: '主页十分可爱的个人小站，记录编程技术学习经历。',
			},
			{
				author: '手里有只毛毛虫',
				desc: '号角声起 - 等你启航',
				link: 'https://www.krjojo.com/',
				feed: 'https://www.krjojo.com/feed',
				icon: 'https://www.krjojo.com/favicon.ico',
				avatar: 'https://www.krjojo.com/wp-content/uploads/2025/02/毛毛虫2.avif',
				archs: ['WordPress', 'Cloudflare'],
				date: '2025-11-29',
				comment: '前端运维和生活思考。',
			},
			{
				author: 'cosine',
				sitenick: '余弦',
				title: '余弦の博客',
				desc: '= WA 的一声就哭了 =',
				link: 'https://blog.cosine.ren/',
				feed: 'https://blog.cosine.ren/rss.xml',
				icon: 'https://blog.cosine.ren/favicon.ico',
				avatar: 'https://blog.cosine.ren/img/avatar.webp',
				archs: ['Astro', 'Vercel'],
				date: '2025-12-07',
				comment: '“FE / ACG / 手工 / 深色模式强迫症 / INFP / 兴趣广泛养两只猫的老宅女 / remote”，运营《前端周周谈 FE Bits》周刊。',
			},
			{
				author: '棋',
				sitenick: 'ImQi1',
				desc: '做技术的分享者、生活的摄影师、时事的评论员。',
				link: 'https://imqi1.com/',
				feed: 'https://imqi1.com/feed/',
				icon: 'https://imqi1.com/favicon.ico',
				avatar: 'https://imqi1.com/avatar.webp',
				archs: ['Typecho', '国内 CDN'],
				date: '2025-12-31',
				comment: '博客技术与生活分享。',
			},
			// #region 2026
			{
				author: '见崎美咲',
				sitenick: 'Catarium',
				desc: '见崎的猫箱',
				link: 'https://catarium.me/',
				feed: 'https://catarium.me/atom.xml',
				icon: 'https://catarium.me/favicon.ico',
				avatar: getGithubAvatar('Eofs791'),
				archs: ['Valaxy', 'Cloudflare'],
				date: '2026-01-02',
				comment: '加拿大留子，二次元。',
			},
			{
				author: '23朵毒蘑菇',
				desc: '一个简单的前端开发者。',
				link: 'https://blog.dumogu.top/',
				feed: 'https://blog.dumogu.top/rss.xml',
				icon: 'https://blog.dumogu.top/web-assets/v-last/public/favicon.ico',
				avatar: 'https://blog.dumogu.top/web-assets/v-last/public/user.jpg',
				archs: ['Express', '服务器'],
				date: '2026-01-06',
				comment: '捣鼓了不少东西的前端程序员。',
			},
			{
				author: 'Viki',
				title: 'Viki 写东西的地方',
				desc: '生活需要记录。',
				link: 'https://blog.viki.moe/',
				feed: 'https://blog.viki.moe/rss',
				icon: 'https://blog.viki.moe/favicon.ico',
				avatar: 'https://blog.viki.moe/avatar.png',
				archs: ['Next.js', 'Vercel'],
				date: '2026-01-19',
				comment: '前端大手子，博客与前端知识分享。',
			},
			{
				author: 'GnixAij',
				desc: 'Life Tracking & Tech Sharing',
				link: 'https://vluv.space/',
				feed: 'https://vluv.space/atom.xml',
				icon: 'https://vluv.space/img/logo_icon.svg',
				avatar: 'https://assets.vluv.space/avatar.webp',
				archs: ['Hexo', 'EdgeOne'],
				date: '2026-02-01',
				comment: '前端技术研究与生活记录。',
			},
			{
				author: 'Mr.Lee',
				sitenick: '里世界',
				desc: 'Welcome to the world of Lee',
				link: 'https://leenet.xyz/',
				feed: 'https://leenet.xyz/atom.xml',
				icon: 'https://leenet.xyz/favicon.svg',
				avatar: 'https://leenet.xyz/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2026-02-21',
				comment: 'TUI风格的Nuxt博客，讲述博客技术学习历程。',
			},
			{
				author: 'bakaptr',
				title: 'Nostalgia Garden',
				desc: 'I\'m a person dedicated to what I am interested in.',
				link: 'https://rua.sh/',
				feed: 'https://rua.sh/rss.xml',
				icon: getGithubIcon('Zhousiru'),
				avatar: getGithubAvatar('Zhousiru'),
				archs: ['Astro', 'Cloudflare'],
				date: '2026-02-25',
				comment: '素未谋面的同事，前端大手子。',
			},
			{
				author: 'LuckyFish',
				title: 'NoName Blog',
				desc: '一条鱼的自娱自乐',
				link: 'https://blog.luckyfishes.site/',
				feed: 'https://blog.luckyfishes.site/rss.xml',
				icon: 'https://blog.luckyfishes.site/favicon.ico',
				avatar: getOicqAvatar('2383690354'),
				archs: ['Next.js', 'Vercel'],
				date: '2026-03-02',
				comment: '“老八校”西建大iOS Club前社长，但任职期间没有苹果设备。',
			},
			{
				author: 'Almango',
				desc: '天真永不消逝，浪漫至死不渝',
				link: 'https://blog.almango.cn/',
				feed: 'https://blog.almango.cn/rss.xml',
				icon: 'https://blog.almango.cn/favicon.png',
				avatar: 'https://www.almango.cn/image/avatar.png',
				archs: ['Astro', 'Vercel'],
				date: '2026-03-22',
				comment: '编程入门、博客搭建、游戏生活为主的个人成长向技术博客，系统记录C#/C++/Python/前端等学习笔记、Hexo/Astro建站与主题开发、MC服务器开服日志，同时包含年度总结与游戏感悟。',
			},
			{
				author: '张小阳',
				sitenick: 'CodeVoy',
				desc: '知识管理与技术分析',
				link: 'https://www.zzyang.top/',
				feed: 'https://www.zzyang.top/rss.xml',
				icon: 'https://www.zzyang.top/favicon/avatar.png',
				avatar: 'https://www.zzyang.top/favicon/avatar.png',
				archs: ['Astro', '服务器'],
				date: '2026-03-28',
				comment: '分享Java后端、数据库与AI实战的技术博客',
			},
			/* ========从此处新增友链======== */
		],
	},
	// #endregion
	// #region XUPTers
	{
		name: 'XUPTers',
		desc: '西安邮电大学的校友们。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '半岛的孤城',
				sitenick: '小屋',
				title: '半岛的小屋',
				desc: '不知道写啥，那就不写了。哎嘿',
				link: 'https://www.bandao.ltd/',
				feed: 'https://www.bandao.ltd/atom.xml',
				icon: getGithubIcon('bandaoworld'),
				avatar: getGithubAvatar('bandaoworld'),
				archs: ['Hexo', '服务器'],
				date: '2024-02-02',
				comment: '大学学长，爱好摄影/听歌，会一些Vue。',
			},
		],
	},
	// #endregion
	// #region 知识分享
	{
		name: '知识分享',
		desc: '“AI时代”创作分享/知识内容收集。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '茂茂物语',
				desc: '茂茂的成长之路，包含前端常用知识、源码阅读笔记、各种奇淫技巧、日常提效工具等',
				link: 'https://notes.fe-mm.com/',
				icon: getGithubIcon('maomao1996'),
				avatar: getGithubAvatar('maomao1996'),
				archs: ['VitePress', 'Cloudflare'],
				date: '2024-02-17',
				comment: '前端开发笔记。',
			},
		],
	},
	// #endregion
	// #region 漫游
	{
		name: '漫游',
		desc: '网上冲浪时发现的精彩内容与常读订阅，与君共享。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '风记星辰',
				desc: '热爱你来过的每度温暖',
				feed: 'https://www.thyuu.com/feed',
				link: 'https://www.thyuu.com/',
				icon: 'https://std.thyuu.com/logo.svg',
				avatar: 'https://std.thyuu.com/logo.svg',
				archs: ['WordPress', '服务器'],
				date: '2024-02-01',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
